### ISSUE TITLE
Videos ended on last frame for short time before it's switches to another video

### ISSUE THREAD

**Issue by centrumkanalen** [signageos/smil-player#1]
Videos freeze for a bit before playing next video. Sometimes it gets dark blue between videos

**Comment by lukdanek** [comment]
Is this related to a specific device? Or are you seeing that on every platform?

**Comment by centrumkanalen** [comment]
This is for Android, sorry. 
LG is instead freezing for around 0,5-1 seconds if conditional play exists in the smil markup

**Comment by lukdanek** [comment]
Try the latest master, it has some improvements to the conditional playback processing.

**Comment by GeorgeMaharis123** [comment]
Hi there
I just tried with the latest master, but still experience a freeze of about 0.5 seconds between videos on Raspberry Pi4. the videos are all the same resolution, framerate, format and codec. (mp4 videos, 1080p, 25fps)
It also happens in the emulator, but the freeze is shorter there and not that noticeable.

**Comment by lukdanek** [comment]
Hi, the RPi 4 has this limitation based on the HW specs and ability to start rendering the videos faster. Its something we are also working on as signageOS, but for not it's given.

**Comment by lukdanek** [comment]
We improved the playback behavior in 1.4.0. Kindly test on your side.
