### ISSUE TITLE
 Video freeze while switching

### ISSUE THREAD

**Issue by rst303** [signageos/smil-player#14]
The Video freeze while loading the content, when switching from a playlist with video to a playlist with AF. 
Tested with Raspberry Pi:

UID (for REST API)
2e3dce4da4d3176c63a219bdd63b8588b81ddf6e50ae52bf08cc4
DUID
D9d7bf621f111f187c730e37f95fa83a05ea7e70552c71bb01

Version 1.4.2_1.7.0100

The smil with the video: https://deploy.screenfood.com/lightplayer/smil/rspivid/asdf and
the smil with the af: https://deploy.screenfood.com/lightplayer/smil/rspiaf/asdf

**Comment by PetrDusek89** [comment]
Hello,

are you switching playlists manually, or does this issue happen when you update your smil file and smil player updates automatically?

**Comment by rst303** [comment]
Hello
We push the new playlist directly from the CMS to the player.

**Comment by timoteoponce** [comment]
Hi @rst303, I think that the visual mechanism is that we push the changes from the CMS, but what happens underneath is this:

    we update the smil file and smil player updates automatically after reaching the refresh interval

**Comment by PetrDusek89** [comment]
Hello,

thanks for the clarification. I will look into it.

**Comment by rst303** [comment]
@PetrDusek89 : I am sorry, the playlist https://deploy.screenfood.com/lightplayer/smil/rspivid/asdf  was changed, now it has that one which creates the issue.

**Comment by PetrDusek89** [comment]
Hello,

I am having hard time reproducing your issue. If it is possible could you please be more specific which video freezes for you and when exactly does this happen?

Thanks Petr

**Comment by PetrDusek89** [comment]
Hello,

this issue should be resolved in latest release. Please upgrade your SMIL player to the latest master (1.8.0).
