### ISSUE TITLE
Black screen during refresh

### ISSUE THREAD

**Issue by naum-mllrdev** [signageos/smil-player#15]
Hi Team,

We are currently testing our playlist through the default SMIL player (v1.7.0) We have added the Refresh meta (as described in https://docs.signageos.io/knowledge-base/signageos-smil-docs-updating-smil-file) as to refresh the display whenever we updated the content of the smilURL. In deed, the display got updated on every update of the smilURL content. However, we noticed that a black screen is displayed on every refresh (before loading/displaying the latest content). Is there a way to get rid of this black screen?

In addition, we have tried adding the preloader but still the black screen is displayed prior to displaying the preloader.

Let us know if you need further details. 

Device used: Raspberry Pi 4 Model B Rev 1.2 (firmware version 1.4.2)
SMIL file content:

`<smil>
    <head>
        <meta http-equiv="Refresh" content="10"/>
        <layout>
            <root-layout width="1920" height="1080" background="#000000"/>
            <region width="1920" height="1080" backgroundColor="#000000" regionName="main" left="0" top="0" z-index="1" mediaAlign="center"/>
        </layout>
    </head>
    <body>
        <par>
            <seq end="__prefetchEnd.endEvent">
                <seq repeatCount="indefinite">
                    <video src="https://signageos-demo.s3.eu-central-1.amazonaws.com/smil/zones/files/loader.mp4"/>
                </seq>
            </seq>
            <seq>
                <prefetch src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810685/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/lq9kiz18clo9w1fl5jlz.png"/>
                <prefetch src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810684/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/jf0fkuwcog0hbf9qxdvw.jpg"/>
                <seq id="__prefetchEnd" dur="1s"/>
            </seq>
            <par begin="__prefetchEnd.endEvent" repeatCount="indefinite">
                <seq expr="compare(time(), '00:00:00') >= 0 and [compare(time(), '23:59:59') <= 0 or [compare(time(), '00:00:00') >= 0 and compare(time(), '00:00:00') < 0]]">
                    <img region="main" dur="10s" src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810685/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/lq9kiz18clo9w1fl5jlz.png" fit="meetBest"/>
                    <img region="main" dur="10s" src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810684/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/jf0fkuwcog0hbf9qxdvw.jpg" fit="meetBest"/>
                </seq>
            </par>
        </par>
    </body>
</smil>`

Thanks,
Noie

**Comment by PetrDusek89** [comment]
Hello,

this issue should be resolved in latest release. Please upgrade your SMIL player to the latest master (1.8.0).
