### ISSUE TITLE
Last image with crossfade transition flickers

### ISSUE THREAD

**Issue by naum-mllrdev** [signageos/smil-player#16]
Hi Support team,

I created a playlist which plays two images where the last image has the crossfade transition. This is played using the default SMIL player. I noticed that there was a flicker (it's like the previous image reappears) during the transition (see attached video). Please let us know how to correct this or if there's a miss on configuring the SMIL file.

`<smil>
    <head>
        <meta http-equiv="Refresh" content="1"/>
        <layout>
            <root-layout width="1920" height="1080" background="#000000"/>
            <region width="1920" height="1080" backgroundColor="#000000" regionName="main" left="0" top="0" z-index="1" mediaAlign="center"/>
            <transition id="fade3s" xml:id="fade3s" type="fade" subtype="crossfade" dur="3s"/>
        </layout>
    </head>
    <body>
        <par>
            <seq>
                <prefetch src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810684/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/jf0fkuwcog0hbf9qxdvw.jpg"/>
                <prefetch src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810685/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/lq9kiz18clo9w1fl5jlz.png"/>
                <seq id="__prefetchEnd" dur="1s"/>
            </seq>
            <par begin="__prefetchEnd.endEvent" repeatCount="indefinite">
                <seq expr="compare(time(), '00:00:00') >= 0 and [compare(time(), '23:59:59') <= 0 or [compare(time(), '00:00:00') >= 0 and compare(time(), '00:00:00') < 0]]">
                    <img region="main" dur="5s" src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810684/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/jf0fkuwcog0hbf9qxdvw.jpg" fit="meetBest"/>
                    <img region="main" dur="5s" transIn="fade3s" src="https://res.cloudinary.com/designage/image/upload/q_auto,f_auto,w_1920,h_1080,/v1625810685/PROFILE/110e1b6c-dc6d-4ce2-8b6e-a31efc86b268/lq9kiz18clo9w1fl5jlz.png" fit="meetBest"/>
                </seq>
            </par>
        </par>
    </body>
</smil>`

Thanks,
Noie

https://user-images.githubusercontent.com/68266097/127135885-a93a8e9c-7855-4dee-8975-1e5b6ecff4b3.mp4

**Comment by naum-mllrdev** [comment]
Device used: Raspberry Pi 4 Model B Rev 1.2 (firmware version 1.4.2)

**Comment by PetrDusek89** [comment]
Hello,

this issue should be resolved in latest release. Please upgrade your SMIL player to the latest master.

**Comment by naum-mllrdev** [comment]
Hi. I have pulled out the latest master to our branch and verified that the issue is fixed. Thanks!
