### ISSUE TITLE
Conditional play certain times a day

### ISSUE THREAD

**Issue by centrumkanalen** [signageos/smil-player#3]
As described here: [a-smil Conditional play](http://www.a-smil.org/index.php/Conditional_play)

**Running this:**
<video src="foo.mp4" expr="adapi-compare('07:00:00', substring-after(adapi-date(), 'T')) &lt;= 0 and 
adapi-compare('11:00:00', substring-after(adapi-date(), 'T')) &gt; 0">

**Expecting**
If NOT between 7:00 - 11:00 - skip the video

**Result**
Skips the video no matter what

**Comment by lukdanek** [comment]
This feature is already supported in the latest master, verified on multiple devices. Can you re-confirm on your end with the latest code?

**Comment by centrumkanalen** [comment]
I think the problem is only for generic Andoid. Worked when updating to latest core app on LG

**Comment by lukdanek** [comment]
Some improvement of the Android behavior is coming in Core App 3.6.0. But this is not related to the SMIL Player itself. Closing this issue as resolved by the latest master.
